
spring:
  application:
    name: "BankingGatewayServer"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

  info:
    env:
      enabled: true



info:
  app:
    name: "BankingGatewayServer"
    description: "This is a BankingGateway Server"
    version: "1.0.0"



